/**
 * 代码块的语言定义表：关键字、行注释/块注释、字符串定界符、别名。
 *
 * 单一职责：只是数据。分词器（./lexer.ts）按它扫描；
 * `@shared/code-language.ts` 的 UI 下拉清单是它的**展示子集**。
 */

export type Mode = 'code' | 'markup' | 'css' | 'data'

export interface LanguageDef {
  mode: Mode
  /** 行注释起始串 */
  lineComment?: string[]
  /** 块注释：[开始, 结束] */
  blockComment?: Array<[string, string]>
  /** 可跨行的字符串（Python 三引号） */
  multilineString?: string[]
  /** 单行字符串引号 */
  strings?: string[]
  keywords?: string[]
  literals?: string[]
  builtins?: string[]
  /** 以大写字母开头的标识符当作类型（类名/结构体名） */
  upperAsType?: boolean
  /** 关键字不区分大小写（SQL） */
  ignoreCase?: boolean
  /** `$var`、`${...}`、`@decorator` 之类的记号 */
  sigils?: string[]
  /** data 模式：`key:` 形式的键（YAML）；JSON 由 `"key":` 规则识别 */
  yamlKeys?: boolean
}

const C_KEYWORDS = [
  'auto',
  'break',
  'case',
  'class',
  'const',
  'continue',
  'default',
  'do',
  'else',
  'enum',
  'explicit',
  'export',
  'friend',
  'goto',
  'if',
  'import',
  'inline',
  'namespace',
  'new',
  'operator',
  'private',
  'protected',
  'public',
  'register',
  'return',
  'sizeof',
  'static',
  'struct',
  'switch',
  'template',
  'this',
  'throw',
  'try',
  'catch',
  'typedef',
  'typename',
  'union',
  'using',
  'virtual',
  'volatile',
  'while',
  'override',
  'final'
]

export const DEFS: Record<string, LanguageDef> = {
  javascript: {
    mode: 'code',
    lineComment: ['//'],
    blockComment: [['/*', '*/']],
    strings: ['"', "'", '`'],
    keywords: [
      'async',
      'await',
      'break',
      'case',
      'catch',
      'class',
      'const',
      'continue',
      'debugger',
      'default',
      'delete',
      'do',
      'else',
      'export',
      'extends',
      'finally',
      'for',
      'from',
      'function',
      'get',
      'if',
      'import',
      'in',
      'instanceof',
      'let',
      'new',
      'of',
      'return',
      'set',
      'static',
      'super',
      'switch',
      'this',
      'throw',
      'try',
      'typeof',
      'var',
      'void',
      'while',
      'with',
      'yield',
      'as',
      'await'
    ],
    literals: ['true', 'false', 'null', 'undefined', 'NaN', 'Infinity'],
    builtins: [
      'Array',
      'Boolean',
      'Date',
      'Error',
      'JSON',
      'Map',
      'Math',
      'Number',
      'Object',
      'Promise',
      'RegExp',
      'Set',
      'String',
      'Symbol',
      'console',
      'document',
      'window',
      'module',
      'require',
      'process',
      'exports'
    ]
  },
  typescript: {
    mode: 'code',
    lineComment: ['//'],
    blockComment: [['/*', '*/']],
    strings: ['"', "'", '`'],
    keywords: [
      'abstract',
      'any',
      'as',
      'asserts',
      'async',
      'await',
      'boolean',
      'break',
      'case',
      'catch',
      'class',
      'const',
      'constructor',
      'continue',
      'declare',
      'default',
      'delete',
      'do',
      'else',
      'enum',
      'export',
      'extends',
      'finally',
      'for',
      'from',
      'function',
      'get',
      'if',
      'implements',
      'import',
      'in',
      'infer',
      'instanceof',
      'interface',
      'is',
      'keyof',
      'let',
      'namespace',
      'never',
      'new',
      'number',
      'object',
      'of',
      'override',
      'private',
      'protected',
      'public',
      'readonly',
      'return',
      'satisfies',
      'set',
      'static',
      'string',
      'super',
      'switch',
      'symbol',
      'this',
      'throw',
      'try',
      'type',
      'typeof',
      'undefined',
      'unique',
      'unknown',
      'var',
      'void',
      'while',
      'yield'
    ],
    literals: ['true', 'false', 'null', 'undefined', 'NaN', 'Infinity'],
    builtins: [
      'Array',
      'Boolean',
      'Date',
      'Error',
      'JSON',
      'Map',
      'Math',
      'Number',
      'Object',
      'Promise',
      'RegExp',
      'Set',
      'String',
      'Symbol',
      'WeakMap',
      'console',
      'document',
      'window',
      'process',
      'Record',
      'Partial',
      'Readonly'
    ],
    upperAsType: true
  },
  python: {
    mode: 'code',
    lineComment: ['#'],
    multilineString: ['"""', "'''"],
    strings: ['"', "'"],
    keywords: [
      'and',
      'as',
      'assert',
      'async',
      'await',
      'break',
      'case',
      'class',
      'continue',
      'def',
      'del',
      'elif',
      'else',
      'except',
      'finally',
      'for',
      'from',
      'global',
      'if',
      'import',
      'in',
      'is',
      'lambda',
      'match',
      'nonlocal',
      'not',
      'or',
      'pass',
      'raise',
      'return',
      'try',
      'while',
      'with',
      'yield'
    ],
    literals: ['True', 'False', 'None'],
    builtins: [
      'abs',
      'all',
      'any',
      'bool',
      'bytes',
      'dict',
      'dir',
      'enumerate',
      'filter',
      'float',
      'format',
      'frozenset',
      'getattr',
      'hasattr',
      'int',
      'isinstance',
      'issubclass',
      'iter',
      'len',
      'list',
      'map',
      'max',
      'min',
      'next',
      'object',
      'open',
      'print',
      'range',
      'repr',
      'reversed',
      'round',
      'self',
      'set',
      'setattr',
      'sorted',
      'str',
      'sum',
      'super',
      'tuple',
      'type',
      'zip'
    ],
    upperAsType: true
  },
  java: {
    mode: 'code',
    lineComment: ['//'],
    blockComment: [['/*', '*/']],
    strings: ['"', "'"],
    keywords: [
      'abstract',
      'assert',
      'boolean',
      'break',
      'byte',
      'case',
      'catch',
      'char',
      'class',
      'const',
      'continue',
      'default',
      'do',
      'double',
      'else',
      'enum',
      'extends',
      'final',
      'finally',
      'float',
      'for',
      'if',
      'implements',
      'import',
      'instanceof',
      'int',
      'interface',
      'long',
      'native',
      'new',
      'package',
      'private',
      'protected',
      'public',
      'record',
      'return',
      'sealed',
      'short',
      'static',
      'strictfp',
      'super',
      'switch',
      'synchronized',
      'this',
      'throw',
      'throws',
      'transient',
      'try',
      'var',
      'void',
      'volatile',
      'while',
      'yield'
    ],
    literals: ['true', 'false', 'null'],
    builtins: [
      'String',
      'System',
      'Integer',
      'Long',
      'Double',
      'Boolean',
      'Object',
      'List',
      'Map',
      'Set',
      'Math',
      'Override'
    ],
    upperAsType: true
  },
  csharp: {
    mode: 'code',
    lineComment: ['//'],
    blockComment: [['/*', '*/']],
    strings: ['"', "'"],
    keywords: [
      'abstract',
      'as',
      'async',
      'await',
      'base',
      'bool',
      'break',
      'byte',
      'case',
      'catch',
      'char',
      'checked',
      'class',
      'const',
      'continue',
      'decimal',
      'default',
      'delegate',
      'do',
      'double',
      'else',
      'enum',
      'event',
      'explicit',
      'extern',
      'finally',
      'fixed',
      'float',
      'for',
      'foreach',
      'get',
      'goto',
      'if',
      'implicit',
      'in',
      'int',
      'interface',
      'internal',
      'is',
      'lock',
      'long',
      'namespace',
      'new',
      'object',
      'operator',
      'out',
      'override',
      'params',
      'private',
      'protected',
      'public',
      'readonly',
      'record',
      'ref',
      'return',
      'sealed',
      'set',
      'short',
      'sizeof',
      'stackalloc',
      'static',
      'string',
      'struct',
      'switch',
      'this',
      'throw',
      'try',
      'typeof',
      'uint',
      'ulong',
      'unchecked',
      'unsafe',
      'ushort',
      'using',
      'var',
      'virtual',
      'void',
      'volatile',
      'while',
      'yield',
      'nameof',
      'when'
    ],
    literals: ['true', 'false', 'null'],
    builtins: [
      'Console',
      'String',
      'Int32',
      'Double',
      'Boolean',
      'Object',
      'List',
      'Dictionary',
      'Task',
      'Math',
      'Enumerable'
    ],
    upperAsType: true
  },
  c: {
    mode: 'code',
    lineComment: ['//'],
    blockComment: [['/*', '*/']],
    strings: ['"', "'"],
    keywords: C_KEYWORDS,
    literals: ['NULL', 'true', 'false'],
    builtins: [
      'printf',
      'scanf',
      'malloc',
      'free',
      'sizeof',
      'strlen',
      'memcpy',
      'FILE',
      'size_t',
      'uint8_t',
      'int32_t'
    ],
    upperAsType: true
  },
  cpp: {
    mode: 'code',
    lineComment: ['//'],
    blockComment: [['/*', '*/']],
    strings: ['"', "'"],
    keywords: [
      ...C_KEYWORDS,
      'nullptr',
      'constexpr',
      'noexcept',
      'concept',
      'requires',
      'co_await',
      'co_return'
    ],
    literals: ['true', 'false', 'nullptr', 'NULL'],
    builtins: [
      'std',
      'cout',
      'cin',
      'endl',
      'string',
      'vector',
      'map',
      'set',
      'unique_ptr',
      'shared_ptr',
      'size_t',
      'auto'
    ],
    upperAsType: true
  },
  go: {
    mode: 'code',
    lineComment: ['//'],
    blockComment: [['/*', '*/']],
    strings: ['"', '`', "'"],
    keywords: [
      'break',
      'case',
      'chan',
      'const',
      'continue',
      'default',
      'defer',
      'else',
      'fallthrough',
      'for',
      'func',
      'go',
      'goto',
      'if',
      'import',
      'interface',
      'map',
      'package',
      'range',
      'return',
      'select',
      'struct',
      'switch',
      'type',
      'var'
    ],
    literals: ['true', 'false', 'nil', 'iota'],
    builtins: [
      'append',
      'cap',
      'close',
      'complex',
      'copy',
      'delete',
      'error',
      'float32',
      'float64',
      'int',
      'int64',
      'len',
      'make',
      'new',
      'panic',
      'print',
      'println',
      'recover',
      'rune',
      'string',
      'uint',
      'uint64',
      'byte'
    ],
    upperAsType: true
  },
  rust: {
    mode: 'code',
    lineComment: ['//'],
    blockComment: [['/*', '*/']],
    strings: ['"', "'"],
    keywords: [
      'as',
      'async',
      'await',
      'break',
      'const',
      'continue',
      'crate',
      'dyn',
      'else',
      'enum',
      'extern',
      'false',
      'fn',
      'for',
      'if',
      'impl',
      'in',
      'let',
      'loop',
      'match',
      'mod',
      'move',
      'mut',
      'pub',
      'ref',
      'return',
      'self',
      'static',
      'struct',
      'super',
      'trait',
      'true',
      'type',
      'unsafe',
      'use',
      'where',
      'while'
    ],
    literals: ['true', 'false', 'None', 'Some', 'Ok', 'Err'],
    builtins: [
      'String',
      'Vec',
      'Box',
      'Option',
      'Result',
      'println',
      'print',
      'format',
      'vec',
      'panic',
      'assert',
      'assert_eq'
    ],
    upperAsType: true,
    sigils: ['#']
  },
  sql: {
    mode: 'code',
    lineComment: ['--'],
    blockComment: [['/*', '*/']],
    strings: ["'", '"'],
    keywords: [
      'add',
      'all',
      'alter',
      'and',
      'as',
      'asc',
      'begin',
      'between',
      'by',
      'case',
      'cast',
      'column',
      'commit',
      'constraint',
      'create',
      'cross',
      'default',
      'delete',
      'desc',
      'distinct',
      'drop',
      'else',
      'end',
      'exists',
      'foreign',
      'from',
      'full',
      'group',
      'having',
      'if',
      'in',
      'index',
      'inner',
      'insert',
      'into',
      'is',
      'join',
      'key',
      'left',
      'like',
      'limit',
      'not',
      'null',
      'offset',
      'on',
      'or',
      'order',
      'outer',
      'primary',
      'references',
      'right',
      'select',
      'set',
      'table',
      'then',
      'union',
      'unique',
      'update',
      'values',
      'view',
      'when',
      'where',
      'with'
    ],
    literals: ['true', 'false', 'null'],
    builtins: [
      'avg',
      'count',
      'coalesce',
      'max',
      'min',
      'now',
      'sum',
      'int',
      'text',
      'varchar',
      'date',
      'timestamp'
    ],
    ignoreCase: true
  },
  json: { mode: 'data', strings: ['"'], literals: ['true', 'false', 'null'] },
  yaml: {
    mode: 'data',
    lineComment: ['#'],
    yamlKeys: true,
    strings: ['"', "'"],
    literals: ['true', 'false', 'null', 'yes', 'no', '~']
  },
  bash: {
    mode: 'code',
    lineComment: ['#'],
    strings: ['"', "'"],
    keywords: [
      'alias',
      'case',
      'cd',
      'do',
      'done',
      'echo',
      'elif',
      'else',
      'esac',
      'eval',
      'exec',
      'exit',
      'export',
      'fi',
      'for',
      'function',
      'if',
      'in',
      'local',
      'read',
      'readonly',
      'return',
      'set',
      'shift',
      'source',
      'then',
      'unset',
      'until',
      'while'
    ],
    literals: ['true', 'false'],
    builtins: [
      'awk',
      'cat',
      'chmod',
      'curl',
      'find',
      'git',
      'grep',
      'head',
      'ls',
      'mkdir',
      'npm',
      'printf',
      'rm',
      'sed',
      'sort',
      'sudo',
      'tail',
      'touch',
      'tr',
      'wc'
    ],
    sigils: ['$']
  },
  html: { mode: 'markup' },
  css: { mode: 'css' }
}

/** 别名 → 语言 id */
export const ALIASES: Record<string, string> = {
  js: 'javascript',
  jsx: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  ts: 'typescript',
  tsx: 'typescript',
  py: 'python',
  python3: 'python',
  cs: 'csharp',
  'c#': 'csharp',
  sh: 'bash',
  shell: 'bash',
  zsh: 'bash',
  yml: 'yaml',
  htm: 'html',
  xml: 'html',
  scss: 'css',
  less: 'css',
  golang: 'go',
  rs: 'rust',
  postgres: 'sql',
  mysql: 'sql',
  text: '',
  plain: '',
  plaintext: ''
}
